import os
from datetime import datetime
import pandas as pd
from typing import Dict, Any

from src.ops.event_logger import get_logger

logger = get_logger()

class WeeklyReportGenerator:
    """
    Generates weekly performance and cost auditing reports.
    Compares portfolio returns against SPY baseline.
    """
    def __init__(self, report_dir: str = "reports"):
        self.report_dir = report_dir
        os.makedirs(self.report_dir, exist_ok=True)
        
    def generate(self, week_end_date: str, portfolio_df: pd.DataFrame, spy_df: pd.DataFrame, consistency_metrics: Dict[str, Any]) -> str:
        """
        Generate markdown report.
        
        Args:
            week_end_date: YYYY-MM-DD
            portfolio_df: DataFrame with ['date', 'daily_return', 'cost_usd']
            spy_df: DataFrame with ['date', 'adj_close']
            consistency_metrics: Dict with inconsistency stats
        """
        # Calculate Base Metrics
        if len(portfolio_df) == 0:
            port_ret = 0.0
            total_cost = 0.0
        else:
            # Simple cumulative return
            port_ret = (1 + portfolio_df['daily_return']).prod() - 1
            total_cost = portfolio_df['cost_usd'].sum()
            
        if len(spy_df) < 2:
            spy_ret = 0.0
        else:
            spy_ret = (spy_df['adj_close'].iloc[-1] / spy_df['adj_close'].iloc[0]) - 1
            
        alpha = port_ret - spy_ret
        
        # Markdown Content
        lines = [
            f"# Weekly Review: {week_end_date}",
            "",
            "## 1. Performance Overview",
            f"- **Portfolio Return**: {port_ret:.2%}",
            f"- **SPY Return**: {spy_ret:.2%}",
            f"- **Relative Alpha**: {alpha:.2%}",
            "",
            "## 2. Execution & Costs",
            f"- **Total Trading Costs (USD)**: ${total_cost:.2f}",
            "",
            "## 3. Signal Consistency",
            f"- **Target Weights Generated**: {consistency_metrics.get('total_signals', 0)}",
            f"- **Orders Submitted**: {consistency_metrics.get('total_orders', 0)}",
            f"- **Inconsistencies Encountered**: {consistency_metrics.get('inconsistencies', 0)}",
            f"- **Inconsistency Rate**: {consistency_metrics.get('inconsistency_rate', 0.0):.2%}",
            "",
            "## 4. Risk Events",
            "- Not triggered. (Stubbed out for Phase E MVP)",
            "",
            "---",
            "*Generated by Quant-MVP Automated Weekly Job*"
        ]
        
        report_md = "\n".join(lines)
        file_path = os.path.join(self.report_dir, f"weekly_review_{week_end_date}.md")
        
        with open(file_path, 'w') as f:
            f.write(report_md)
            
        logger.info("weekly_report_generated", {"path": file_path, "week": week_end_date})
        return file_path
